# Generated by Django 6.0.2 on 2026-02-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyInventoryApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
